version: '3.9'

services:
  go-app:
    container_name: medods-app
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:postgres@go_db:5432/postgres?sslmode=disable"
      JWT_SECRET: "medods-company"
    ports:
      - "8080:8080"
    depends_on:
      - go_db
  go_db:
    container_name: postgres_container_medods
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
networks:
  default:
    driver: bridge
